# Site settings
baseurl = "https://d2one.ru/"
themesDir = "themes/"
languageCode = "ru-ru"
title = "Kuznetsov Daniil blog"
theme =   "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-105273978-1"
# Disable comments by leaving disqusShortname empty
#disqusShortname = "spf13"

[params]
	name = "Daniil Kuznetsov"
	description = "personal blog"
	bio = "Programmer"
	# Enter optionally your twitter account
	#twitter = "Your Twitter account"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I'm a programmer."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    github-square   = "https://www.github.com/d2one"
    linkedin-square   = "https://www.linkedin.com/in/daniil-kuznetsov-31270691/"
    vk   = "https://vk.com/d2one"
    instagram   = "http://instagram.com/kuznetsovdaniil"
    rss-square = "https://d2one.ru/index.xml"
